global:
  scrape_interval: 15s
  scrape_timeout: "10s"
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['192.168.1.200:9093']

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: 
        labels:
          env: env
          role: docker



