version: '3'
services:
  mysql:
    restart: always
    image: mysql:8
    container_name: mysql-lable
    volumes:
      - ./apps/mysql/mydir:/mydir
      - ./apps/mysql/datadir:/var/lib/mysql
      - ./apps/mysql/conf/my.cnf:/etc/my.cnf
      - ./apps/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=test"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306