// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kratosent/ent/department"
	"kratosent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepartmentUpdate is the builder for updating Department entities.
type DepartmentUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentMutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (du *DepartmentUpdate) Where(ps ...predicate.Department) *DepartmentUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetIsDeleted sets the "is_deleted" field.
func (du *DepartmentUpdate) SetIsDeleted(i int8) *DepartmentUpdate {
	du.mutation.ResetIsDeleted()
	du.mutation.SetIsDeleted(i)
	return du
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableIsDeleted(i *int8) *DepartmentUpdate {
	if i != nil {
		du.SetIsDeleted(*i)
	}
	return du
}

// AddIsDeleted adds i to the "is_deleted" field.
func (du *DepartmentUpdate) AddIsDeleted(i int8) *DepartmentUpdate {
	du.mutation.AddIsDeleted(i)
	return du
}

// SetUpdateAt sets the "update_at" field.
func (du *DepartmentUpdate) SetUpdateAt(t time.Time) *DepartmentUpdate {
	du.mutation.SetUpdateAt(t)
	return du
}

// SetName sets the "name" field.
func (du *DepartmentUpdate) SetName(s string) *DepartmentUpdate {
	du.mutation.SetName(s)
	return du
}

// SetParentDepartmentID sets the "parent_department_id" field.
func (du *DepartmentUpdate) SetParentDepartmentID(i int64) *DepartmentUpdate {
	du.mutation.ResetParentDepartmentID()
	du.mutation.SetParentDepartmentID(i)
	return du
}

// SetNillableParentDepartmentID sets the "parent_department_id" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableParentDepartmentID(i *int64) *DepartmentUpdate {
	if i != nil {
		du.SetParentDepartmentID(*i)
	}
	return du
}

// AddParentDepartmentID adds i to the "parent_department_id" field.
func (du *DepartmentUpdate) AddParentDepartmentID(i int64) *DepartmentUpdate {
	du.mutation.AddParentDepartmentID(i)
	return du
}

// ClearParentDepartmentID clears the value of the "parent_department_id" field.
func (du *DepartmentUpdate) ClearParentDepartmentID() *DepartmentUpdate {
	du.mutation.ClearParentDepartmentID()
	return du
}

// Mutation returns the DepartmentMutation object of the builder.
func (du *DepartmentUpdate) Mutation() *DepartmentMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DepartmentUpdate) Save(ctx context.Context) (int, error) {
	du.defaults()
	return withHooks[int, DepartmentMutation](ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DepartmentUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DepartmentUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DepartmentUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DepartmentUpdate) defaults() {
	if _, ok := du.mutation.UpdateAt(); !ok {
		v := department.UpdateDefaultUpdateAt()
		du.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DepartmentUpdate) check() error {
	if v, ok := du.mutation.Name(); ok {
		if err := department.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Department.name": %w`, err)}
		}
	}
	return nil
}

func (du *DepartmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.IsDeleted(); ok {
		_spec.SetField(department.FieldIsDeleted, field.TypeInt8, value)
	}
	if value, ok := du.mutation.AddedIsDeleted(); ok {
		_spec.AddField(department.FieldIsDeleted, field.TypeInt8, value)
	}
	if value, ok := du.mutation.UpdateAt(); ok {
		_spec.SetField(department.FieldUpdateAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.ParentDepartmentID(); ok {
		_spec.SetField(department.FieldParentDepartmentID, field.TypeInt64, value)
	}
	if value, ok := du.mutation.AddedParentDepartmentID(); ok {
		_spec.AddField(department.FieldParentDepartmentID, field.TypeInt64, value)
	}
	if du.mutation.ParentDepartmentIDCleared() {
		_spec.ClearField(department.FieldParentDepartmentID, field.TypeInt64)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DepartmentUpdateOne is the builder for updating a single Department entity.
type DepartmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentMutation
}

// SetIsDeleted sets the "is_deleted" field.
func (duo *DepartmentUpdateOne) SetIsDeleted(i int8) *DepartmentUpdateOne {
	duo.mutation.ResetIsDeleted()
	duo.mutation.SetIsDeleted(i)
	return duo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableIsDeleted(i *int8) *DepartmentUpdateOne {
	if i != nil {
		duo.SetIsDeleted(*i)
	}
	return duo
}

// AddIsDeleted adds i to the "is_deleted" field.
func (duo *DepartmentUpdateOne) AddIsDeleted(i int8) *DepartmentUpdateOne {
	duo.mutation.AddIsDeleted(i)
	return duo
}

// SetUpdateAt sets the "update_at" field.
func (duo *DepartmentUpdateOne) SetUpdateAt(t time.Time) *DepartmentUpdateOne {
	duo.mutation.SetUpdateAt(t)
	return duo
}

// SetName sets the "name" field.
func (duo *DepartmentUpdateOne) SetName(s string) *DepartmentUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetParentDepartmentID sets the "parent_department_id" field.
func (duo *DepartmentUpdateOne) SetParentDepartmentID(i int64) *DepartmentUpdateOne {
	duo.mutation.ResetParentDepartmentID()
	duo.mutation.SetParentDepartmentID(i)
	return duo
}

// SetNillableParentDepartmentID sets the "parent_department_id" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableParentDepartmentID(i *int64) *DepartmentUpdateOne {
	if i != nil {
		duo.SetParentDepartmentID(*i)
	}
	return duo
}

// AddParentDepartmentID adds i to the "parent_department_id" field.
func (duo *DepartmentUpdateOne) AddParentDepartmentID(i int64) *DepartmentUpdateOne {
	duo.mutation.AddParentDepartmentID(i)
	return duo
}

// ClearParentDepartmentID clears the value of the "parent_department_id" field.
func (duo *DepartmentUpdateOne) ClearParentDepartmentID() *DepartmentUpdateOne {
	duo.mutation.ClearParentDepartmentID()
	return duo
}

// Mutation returns the DepartmentMutation object of the builder.
func (duo *DepartmentUpdateOne) Mutation() *DepartmentMutation {
	return duo.mutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (duo *DepartmentUpdateOne) Where(ps ...predicate.Department) *DepartmentUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DepartmentUpdateOne) Select(field string, fields ...string) *DepartmentUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Department entity.
func (duo *DepartmentUpdateOne) Save(ctx context.Context) (*Department, error) {
	duo.defaults()
	return withHooks[*Department, DepartmentMutation](ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DepartmentUpdateOne) SaveX(ctx context.Context) *Department {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DepartmentUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DepartmentUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DepartmentUpdateOne) defaults() {
	if _, ok := duo.mutation.UpdateAt(); !ok {
		v := department.UpdateDefaultUpdateAt()
		duo.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DepartmentUpdateOne) check() error {
	if v, ok := duo.mutation.Name(); ok {
		if err := department.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Department.name": %w`, err)}
		}
	}
	return nil
}

func (duo *DepartmentUpdateOne) sqlSave(ctx context.Context) (_node *Department, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Department.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, department.FieldID)
		for _, f := range fields {
			if !department.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != department.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.IsDeleted(); ok {
		_spec.SetField(department.FieldIsDeleted, field.TypeInt8, value)
	}
	if value, ok := duo.mutation.AddedIsDeleted(); ok {
		_spec.AddField(department.FieldIsDeleted, field.TypeInt8, value)
	}
	if value, ok := duo.mutation.UpdateAt(); ok {
		_spec.SetField(department.FieldUpdateAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.ParentDepartmentID(); ok {
		_spec.SetField(department.FieldParentDepartmentID, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.AddedParentDepartmentID(); ok {
		_spec.AddField(department.FieldParentDepartmentID, field.TypeInt64, value)
	}
	if duo.mutation.ParentDepartmentIDCleared() {
		_spec.ClearField(department.FieldParentDepartmentID, field.TypeInt64)
	}
	_node = &Department{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
