version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2190:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zoo
      - ZOO_SERVER_PASSWORDS=zoo
      - ZOO_CLIENT_USER=zoo
      - ZOO_CLIENT_PASSWORD=zoo
  kafka1:
    depends_on:
      - zookeeper
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '19092:9093'
    environment:
      - KAFKA_BROKER_ID = 1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka1:9092,CLIENT://kafka1:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,CLIENT://localhost:19092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTEN_USER=kafka
      - KAFKA_LISTEN_PASSWORD=kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zoo
      - KAFKA_ZOOKEEPER_PASSWORD=zoo

  