# 服务
server:
  http:
    addr: 192.168.106.27:8000
    timeout: 1s
  grpc:
    addr: 192.168.106.27:9000
    timeout: 1s
  websocket:
    addr: 192.168.106.27:9001

# 注册中心
register:
  polaris:
    addrs:
      - 192.168.106.27:8091
    namespace: kratosent  
# 配置中心
mid_config:
  addrs:
    - 192.168.106.27:8091
  namespace: default
  file_group: polaris
  file_name: config.yaml

# 数据源
data:
  database:
    driver: mysql
    source: root:123456@tcp(192.168.106.27:3306)/test?parseTime=true&charset=utf8
  redis:
    addr: 192.168.106.27:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

  #grpc
  department:
    addrs:
      - 192.168.106.27:8091
    namespace: kratosent    

# 中间件
middleware:
  prometheus:
    histogram:
      namespace: server
      subsystem: requests
      name: duration_sec
    counter:
      namespace: client
      subsystem: requests
      name: code_total

# 日志
log:
  level: Debug
  file: ./log/test.log
  max_size: 10
  max_backup: 5
  max_age: 30
  compress: false