server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

register:
  polaris:
    addrs:
      - 127.0.0.1:8091
    namespace: kratosent  
mid_config:
  addrs:
    - 127.0.0.1:8091
  namespace: default
  file_group: polaris
  file_name: config.yaml

data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/test?parseTime=true&charset=utf8
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  department:
    addrs:
      - 127.0.0.1:8091
    namespace: kratosent    