# This is a basic workflow to help you get started with Actions

name: Demo-test
env:
  branch-name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  create:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world! ${{github.ref}} $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo ${{secrets.DOCKER_PASSWORD}}
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
      - name: Get Branch
        run: |
         raw=$(git branch -r --contains ${{ github.ref }})
         branch=${raw/origin\/}
        env:
          branch-name: $branch

      - name: Extract metadata (tag, labels) for docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: jacobli/web-server
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
            
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.